import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import "./index.css";
import { Content } from "./Content.jsx";

createRoot(document.getElementById("root")).render(
  <StrictMode>
    <Content />
  </StrictMode>,
);

//EL PLAN:
//1.- CREAR EL TITULO DE LA  PAGINA: HECHO
//2.- CREAR LOS SCOR Y BEST SCORE: HECHO
// 3.- CREAR LAS TARJETAS CON CONTENIDO CHAFA, QUE SEAN NADA MAS 4: HECHO
// 4.- APLICAR EL PRETTY: HECHO
// 4.- IMPLEMENTAR LOGICA DE PRESIONAR CARTA Y HACER UQE SUBA EL SCROE: EN PROCESO
//5.- HACER QUE LAS CARTAS SE MUEVEN TRAS CADA CLICK: NO HECHO
// 6.- HACER QUE AL CRARGAR LA PAGINA APAREZCAN DE FORMA ALEATORIA: NO HECHO
//7.- AGREGAR TODAS LAS TARJETAS: NO HECHO
//8.- PONER IMAGENES CHAFAS DE PRUEBA: NO HECHO
//9.- AGREGAR LOGICA PARA EL BESTSCORE: NO HECHO
//9.- USAR EL API: NO HECHO
//10.- COMENTAR EL CODIGO: NO HEHCO
