import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import "./index.css";
import { Content } from "./Content.jsx";

createRoot(document.getElementById("root")).render(
  <StrictMode>
    <Content />
  </StrictMode>,
);

//EL PLAN:
//1.- CREAR EL TITULO DE LA  PAGINA: HECHO
//2.- CREAR LOS SCOR Y BEST SCORE: HECHO
// 3.- CREAR LAS TARJETAS CON CONTENIDO CHAFA, QUE SEAN NADA MAS 4: HECHO
// 4.- APLICAR EL PRETTY: HECHO
// 4.- IMPLEMENTAR LOGICA DE PRESIONAR CARTA Y HACER UQE SUBA EL SCROE: HECHO
//5.- HACER QUE LAS CARTAS SE MUEVEN TRAS CADA CLICK: HECHO
// 6.- HACER QUE AL CRARGAR LA PAGINA APAREZCAN DE FORMA ALEATORIA: HECHO
//7.- AGREGAR TODAS LAS TARJETAS: HECHO
//8.- PONER IMAGENES CHAFAS DE PRUEBA: HECHO
//9.- AGREGAR LOGICA PARA EL BESTSCORE: HECHO
//9.- USAR EL API: HECHO
//10.- COMENTAR EL CODIGO: NO HEHCO
//11 .- DIVIDIR EN FOLDERS: NO HEHCO
// 12.- USAR EL PRETTY Y ACABAMOS: NO HEHCO
